apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-cm
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-cmd-params-cm
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-gpg-keys-cm
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-notifications-cm
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-rbac-cm
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-ssh-known-hosts-cm
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
data:
  ssh_known_hosts: {{ .Values.sshKnownHostsCm.sshKnownHosts | toYaml | indent 1 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argo.fullname" . }}-tls-certs-cm
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}