apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo.fullname" . }}-application-controller
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "argo.fullname" . }}-application-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "argo.fullname" . }}-application-controller'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo.fullname" . }}-applicationset-controller
  labels:
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "argo.fullname" . }}-applicationset-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "argo.fullname" . }}-applicationset-controller'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo.fullname" . }}-dex-server
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "argo.fullname" . }}-dex-server'
subjects:
- kind: ServiceAccount
  name: '{{ include "argo.fullname" . }}-dex-server'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo.fullname" . }}-notifications-controller
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "argo.fullname" . }}-notifications-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "argo.fullname" . }}-notifications-controller'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo.fullname" . }}-redis
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "argo.fullname" . }}-redis'
subjects:
- kind: ServiceAccount
  name: '{{ include "argo.fullname" . }}-redis'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argo.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "argo.fullname" . }}-server'
subjects:
- kind: ServiceAccount
  name: '{{ include "argo.fullname" . }}-server'
  namespace: '{{ .Release.Namespace }}'