apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo.fullname" . }}-notifications-secret
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argo.fullname" . }}-secret
  labels:
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
type: Opaque