apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-application-controller
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.applicationController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-applicationset-controller
  labels:
    app.kubernetes.io/component: applicationset-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.applicationsetController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-dex-server
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.dexServer.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-notifications-controller
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.notificationsController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-redis
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.redis.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-repo-server
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.repoServer.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo.fullname" . }}-server
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argocd
  {{- include "argo.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.server.serviceAccount.annotations | nindent 4 }}